// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService provides file I/O operations for the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ReadFile reads the content of a file at the given path
 */
export function ReadFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(88318641, path);
}

/**
 * WriteFile writes content to a file at the given path
 */
export function WriteFile(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3601323672, path, content);
}
