#!/bin/bash

# Script to bump version numbers across the project
# Usage: ./scripts/bump-version.sh [major|minor|patch]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
VERSION_FILE="$PROJECT_ROOT/version.json"
CONFIG_FILE="$PROJECT_ROOT/build/config.yml"
FRONTEND_PACKAGE="$PROJECT_ROOT/frontend/package.json"

# Check if version.json exists
if [ ! -f "$VERSION_FILE" ]; then
    echo "Error: version.json not found at $VERSION_FILE"
    exit 1
fi

# Get current version
CURRENT_VERSION=$(node -p "require('$VERSION_FILE').version")
BUILD_NUMBER=$(node -p "require('$VERSION_FILE').buildNumber")

echo "Current version: $CURRENT_VERSION (build $BUILD_NUMBER)"

# Determine bump type
BUMP_TYPE="${1:-patch}"

if [ "$BUMP_TYPE" != "major" ] && [ "$BUMP_TYPE" != "minor" ] && [ "$BUMP_TYPE" != "patch" ]; then
    echo "Error: Invalid bump type. Use 'major', 'minor', or 'patch'"
    exit 1
fi

# Parse current version
IFS='.' read -r -a VERSION_PARTS <<< "$CURRENT_VERSION"
MAJOR="${VERSION_PARTS[0]}"
MINOR="${VERSION_PARTS[1]}"
PATCH="${VERSION_PARTS[2]}"

# Bump version based on type
case $BUMP_TYPE in
    major)
        MAJOR=$((MAJOR + 1))
        MINOR=0
        PATCH=0
        ;;
    minor)
        MINOR=$((MINOR + 1))
        PATCH=0
        ;;
    patch)
        PATCH=$((PATCH + 1))
        ;;
esac

NEW_VERSION="$MAJOR.$MINOR.$PATCH"
NEW_BUILD_NUMBER=$((BUILD_NUMBER + 1))

echo "New version: $NEW_VERSION (build $NEW_BUILD_NUMBER)"

# Ask for confirmation
read -p "Proceed with version bump? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Version bump cancelled"
    exit 0
fi

# Update version.json
cat > "$VERSION_FILE" << EOF
{
  "version": "$NEW_VERSION",
  "buildNumber": $NEW_BUILD_NUMBER
}
EOF

echo "✓ Updated version.json"

# Update build/config.yml
if [ -f "$CONFIG_FILE" ]; then
    # Use sed to replace version in config.yml (cross-platform compatible)
    if [[ "$OSTYPE" == "darwin"* ]]; then
        sed -i '' "s/version: \".*\"/version: \"$NEW_VERSION\"/" "$CONFIG_FILE"
    else
        sed -i "s/version: \".*\"/version: \"$NEW_VERSION\"/" "$CONFIG_FILE"
    fi
    echo "✓ Updated build/config.yml"
fi

# Update frontend/package.json
if [ -f "$FRONTEND_PACKAGE" ]; then
    node -e "
        const fs = require('fs');
        const pkg = JSON.parse(fs.readFileSync('$FRONTEND_PACKAGE', 'utf8'));
        pkg.version = '$NEW_VERSION';
        fs.writeFileSync('$FRONTEND_PACKAGE', JSON.stringify(pkg, null, 2) + '\n');
    "
    echo "✓ Updated frontend/package.json"
fi

# Generate Go version file
GO_VERSION_FILE="$PROJECT_ROOT/version.go"
cat > "$GO_VERSION_FILE" << EOF
package main

// Auto-generated by scripts/bump-version.sh
// DO NOT EDIT MANUALLY

const (
	Version     = "$NEW_VERSION"
	BuildNumber = $NEW_BUILD_NUMBER
)
EOF

echo "✓ Generated version.go"

# Create git tag
echo ""
echo "Creating git tag v$NEW_VERSION..."
git add "$VERSION_FILE" "$CONFIG_FILE" "$FRONTEND_PACKAGE" "$GO_VERSION_FILE" 2>/dev/null || true
git commit -m "chore: bump version to $NEW_VERSION (build $NEW_BUILD_NUMBER)" 2>/dev/null || true
git tag -a "v$NEW_VERSION" -m "Release v$NEW_VERSION" 2>/dev/null || {
    echo "Note: Could not create git tag (maybe not in a git repo or tag already exists)"
}

echo ""
echo "✅ Version bump complete!"
echo "   Version: $CURRENT_VERSION → $NEW_VERSION"
echo "   Build: $BUILD_NUMBER → $NEW_BUILD_NUMBER"
echo ""
echo "Next steps:"
echo "  1. Review changes: git status"
echo "  2. Push changes: git push && git push --tags"
echo "  3. Build release: make build-all"
echo "  4. Package installers: make package-all"
